language: python
python:
  - 2.7

services:
  - docker

before_install:
  # update is required to update the repositories to see the new packages for
  # Docker.
  - sudo apt-get update
  - docker-compose --version
  - pip install docker-compose --upgrade
  - docker-compose --version


install:
  - cd dockerfiles/build
  - docker-compose build
  - docker-compose up -d
  - docker-compose ps


before_script:
  - pip install requests
  - pip install docker
  - cd $TRAVIS_BUILD_DIR


script:
  - bash ./.travis/linters.sh
  - python tests.py


notifications:
  slack:
    rooms:
      - optimum-team:GycletOWK4Kt95GktwYwfUMp#build


after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=trydirect/symfony4-restful
  - export TAG=app
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
