version: "2"

volumes:
    db:
      driver: local

services:

  php:
    image: trydirect/symfony:latest
    restart: always
    container_name: php
    env_file:
         - symfony/.env
    user: 1001:1001
    links:
      - db
    working_dir: /var/www/html
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rest_api
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      XDEBUG_CONFIG: remote_host=0.0.0.0
    volumes:
      - ./symfony:/var/www/html
      - ./www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./xdebug.ini:/usr/local/lib/php/doc/xdebug/xdebug.ini


  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      depends_on:
        - db
      ports:
        - 8080:80
      volumes:
        - /sessions


  elasticsearch:
    image: elasticsearch:5.4
    restart: always
    container_name: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: "single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    links:
      - php
    depends_on:
      - php
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data

  kibana:
      image: kibana:5.4
      restart: always
      container_name: kibana
      depends_on:
        - elasticsearch
      ports:
        - "5601:5601"
      links:
        - elasticsearch

  logstash:
      image: logstash:5.4
      container_name: logstash
      restart: always
      ports:
        - "5044"
      links:
        - elasticsearch
      depends_on:
        - elasticsearch

  redis:
      image: redis:latest
      restart: always
      container_name: redis
      env_file:
        - symfony/.env
      volumes:
        - ./redis-data:/data

  db:
    image: mysql:5.7
    restart: always
    container_name: mysql57-container
    ports:
      - "127.0.0.1:3357:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rest_api
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      DB_CONNECTION: mysql
    volumes:
#      - ./docker/dbdata:/var/lib/mysql
      - db:/var/lib/mysql

# entry point
  nginx:
    image: ${REGISTRY}trydirect/nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"
    links:
      - php
    volumes:
      - ./certs/ssl:/etc/nginx/ssl
      - ./certs/letsencrypt:/etc/letsencrypt
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./supervisord:/etc/supervisor/conf.d/
      - ./cron/nginx:/var/spool/cron/crontabs
      - ./symfony:/var/www/html
    entrypoint: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf -n
