# configs/filebeat/filebeat.yml

filebeat.prospectors:
- type: log
  enabled: true
  paths:
    - /var/lib/docker/containers/*/*.log
  processors:
    - add_docker_metadata: ~
  fields:
      enviroment: dev
      instance: symfony.local
      project: symfony
  json.message_key: log
  fields_under_root: true
  exclude_lines: ['.*container_cadvisor.*']
  exclude_lines: ['*cadvisor*']
  exclude_lines: ['cadvisor']
  exclude_files: ['.gz$']
#----------------------------- Logstash output --------------------------------
output.logstash:
  hosts: ["logstash:5044"]
